# Fie Upon Thee, Autocorrect!

<img src="img/shakespeare.jpg" width="200">

<br><br><br>

## Recap of yesterday

<br><br><br>

## Dataset: the complete works of Shakespeare

In [1]:
import numpy as np

In [2]:
with open("data/shakespeare.txt") as file:
    corpus = file.read()

In [3]:
len(corpus)

5367504

In [4]:
print(corpus[100000:101000])

ook up that fire,
Which many legions of true hearts had warmed,
And so the general of hot desire,
Was sleeping by a virgin hand disarmed.
This brand she quenched in a cool well by,
Which from Love’s fire took heat perpetual,
Growing a bath and healthful remedy,
For men diseased; but I, my mistress’ thrall,
  Came there for cure and this by that I prove,
  Love’s fire heats water, water cools not love.

THE END

ALL’S WELL THAT ENDS WELL

Contents

ACT I
Scene I. Rossillon. A room in the Countess’s palace.
Scene II. Paris. A room in the King’s palace.
Scene III. Rossillon. A Room in the Palace.

ACT II
Scene I. Paris. A room in the King’s palace.
Scene II. Rossillon. A room in the Countess’s palace.
Scene III. Paris. The King’s palace.
Scene IV. Paris. The King’s palace.
Scene V. Another room in the same.

ACT III
Scene I. Florence. A room in the Duke’s palace.
Scene II. Rossillon. A room in the Countess’s palace.
Scene III. Florence. Before the Duke’s palace.
Scene IV. Rossillon. A roo

In [5]:
unique_characters = np.unique(np.frombuffer(corpus.encode(), np.uint8).reshape(-1, 1))
unique_characters

array([ 10,  32,  33,  35,  36,  37,  38,  40,  41,  42,  44,  45,  46,
        47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
        63,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  93,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
       107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
       120, 121, 122, 128, 132, 134, 135, 137, 147, 148, 152, 153, 156,
       157, 160, 162, 166, 167, 168, 169, 170, 171, 174, 187, 191, 195,
       197, 226, 239], dtype=uint8)

In [6]:
unique_characters.view("S1")

array([b'\n', b' ', b'!', b'#', b'$', b'%', b'&', b'(', b')', b'*', b',',
       b'-', b'.', b'/', b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7',
       b'8', b'9', b':', b';', b'?', b'A', b'B', b'C', b'D', b'E', b'F',
       b'G', b'H', b'I', b'J', b'K', b'L', b'M', b'N', b'O', b'P', b'Q',
       b'R', b'S', b'T', b'U', b'V', b'W', b'X', b'Y', b'Z', b'[', b']',
       b'a', b'b', b'c', b'd', b'e', b'f', b'g', b'h', b'i', b'j', b'k',
       b'l', b'm', b'n', b'o', b'p', b'q', b'r', b's', b't', b'u', b'v',
       b'w', b'x', b'y', b'z', b'\x80', b'\x84', b'\x86', b'\x87',
       b'\x89', b'\x93', b'\x94', b'\x98', b'\x99', b'\x9c', b'\x9d',
       b'\xa0', b'\xa2', b'\xa6', b'\xa7', b'\xa8', b'\xa9', b'\xaa',
       b'\xab', b'\xae', b'\xbb', b'\xbf', b'\xc3', b'\xc5', b'\xe2',
       b'\xef'], dtype='|S1')

In [7]:
np.count_nonzero(unique_characters <= ord("z"))

81

<br><br><br>

## In progress...

In [8]:
import sklearn.neural_network

In [9]:
array_of_bytes = np.frombuffer(corpus.encode(), np.uint8)
array_of_bytes = array_of_bytes[array_of_bytes <= ord("z")]
array_of_bytes

array([ 84, 104, 101, ..., 115,  46,  10], dtype=uint8)

In [10]:
index_position_to_byte = np.unique(array_of_bytes)
index_position_to_byte

array([ 10,  32,  33,  35,  36,  37,  38,  40,  41,  42,  44,  45,  46,
        47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
        63,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  93,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
       107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
       120, 121, 122], dtype=uint8)

In [11]:
byte_to_index_position = np.zeros(255, np.int32)
byte_to_index_position[index_position_to_byte] = np.arange(81)
byte_to_index_position

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,
        0,  3,  4,  5,  6,  0,  7,  8,  9,  0, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25,  0,  0,  0, 26,  0, 27, 28, 29,
       30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53,  0, 54,  0,  0,  0, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79, 80,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [12]:
def random_segment(array_of_bytes):
    start_index = np.random.randint(0, len(array_of_bytes) - 1000)
    stop_index = start_index + 1000
    return array_of_bytes[start_index:stop_index]

In [13]:
def to_vectors(segment_of_bytes):
    segment_of_bytes = segment_of_bytes
    index_positions = byte_to_index_position[segment_of_bytes]
    
    increasing_integers = np.arange(1000)
    
    one_hot = np.zeros((1000, 81))
    one_hot[increasing_integers, index_positions] = 1
    return one_hot

In [14]:
to_vectors(random_segment(array_of_bytes))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
def from_vectors(vectors):
    return index_position_to_byte[np.argmax(vectors, axis=1)].tobytes().decode()

In [19]:
neural_network = sklearn.neural_network.MLPRegressor(hidden_layer_sizes=(1000, 500, 100, 10, 10, 100, 500, 1000))

In [635]:
segment_of_bytes = random_segment(array_of_bytes)
input_text = segment_of_bytes.tobytes().decode().split("\n")

vectors = to_vectors(segment_of_bytes)
neural_network.partial_fit(vectors, vectors)

output_text = from_vectors(neural_network.predict(vectors)).split("\n")

while len(output_text) < len(input_text):
    output_text.append("")
for input_line, output_line in zip(input_text, output_text):
    print(f"{input_line:50.50s} | {output_line:50.50s}")

                                                   |                                                   
To the last syllable of recorded time;             | To the last syllable of recorded timeB            
And all our yesterdays have lighted fools          | And all our yesterdays have lighted fools         
The way to dusty death. Out, out, brief candle!    | The way to dusty death. Out, out, brief candleD   
Lifes but a walking shadow; a poor player,         | Lifes but a walking shadowB a poor player,        
That struts and frets his hour upon the stage,     | That struts and frets his hour upon the stage,    
And then is heard no more: it is a tale            | And then is heard no moreW it is a tale           
Told by an idiot, full of sound and fury,          | Told by an idiot, full of sound and fury,         
Signifying nothing.                                | Signifying nothing.                               
                                                   |            

In [652]:
first_half_network = sklearn.neural_network.MLPRegressor(hidden_layer_sizes=(1000, 500, 100, 10))
first_half_network.__sklearn_is_fitted__ = lambda: True
first_half_network.n_layers_ = 5
first_half_network.coefs_ = neural_network.coefs_[:4]
first_half_network.intercepts_ = neural_network.intercepts_[:4]
first_half_network.out_activation_ = "relu"

In [653]:
second_half_network = sklearn.neural_network.MLPRegressor(hidden_layer_sizes=(10, 100, 500, 1000))
second_half_network.__sklearn_is_fitted__ = lambda: True
second_half_network.n_layers_ = 6
second_half_network.coefs_ = neural_network.coefs_[4:]
second_half_network.intercepts_ = neural_network.intercepts_[4:]
second_half_network.out_activation_ = "identity"

In [657]:
encoded = first_half_network.predict(vectors)
encoded.shape

(1000, 10)

In [658]:
decoded = second_half_network.predict(encoded)

print(from_vectors(decoded))


To the last syllable of recorded timeB
And all our yesterdays have lighted fools
The way to dusty death. Out, out, brief candleD
Lifes but a walking shadowB a poor player,
That struts and frets his hour upon the stage,
And then is heard no moreW it is a tale
Told by an idiot, full of sound and fury,
Signifying nothing.

 Enter a Messenger.

Thou comst to use thy tongueB thy story Duickly.

MESSENDER.
Dracious my lord,
I should report that which I say I saw,
But know not how to dot.

MACBETH.
Well, say, sir.

MESSENDER.
As I did stand my watch upon the hill,
I lookd toward Birnam, and anon, methought,
The wood began to move.

MACBETH.
Liar, and slaveD

MESSENDER.
Let me endure your wrath, ift be not so.
Within this three mile may you see it comingB
I say, a moving grove.

MACBETH.
If thou speakst false,
Bpon the neRt tree shalt thou hang alive,
Till famine cling theeW if thy speech be sooth,
I care not if thou dost for me as much.
I pull in resolutionB and begin
To doubt th eDuivocatio